# Generated by Django 5.0 on 2025-02-05 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_patient_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 5, 12, 2, 29, 991400, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
