# Generated by Django 5.0 on 2025-02-05 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_patient_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 5, 12, 4, 52, 575963, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
